---
- name: "Deploy app from {{ path_to_app }}"
  ansible.builtin.include_role:
    name: wildfly_utils
    tasks_from: jboss_cli.yml
  vars:
    jboss_cli_query: "'deploy --force {{ path_to_app }}'"
    jboss_cli_changed_when: True
    jboss_cli_controller_port: "{{ (id * 100) + 9990 | int }}"

- name: "Check that app is reachable {{ app_path }} (on instance {{ id }})"
  ansible.builtin.get_url:
    url: "http://localhost:8{{ id }}80{{ app_path }}"
    dest: '/tmp/results.txt'
  changed_when: False
