---
- name: EDA lab
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "http://10.0.148.18:8080/info/"
        delay: 10
  rules:
    - name: "Restart Wildfly if url is not reachable"
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "EDA Restart Wildfly"
          organization: "wildfly-cluster"
