---
- name: "Move any messages in the DLQ to another queue for processing"
  hosts: wildfly
  gather_facts: False
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Retrieve Cluster Config"
      ansible.builtin.include_tasks: tasks/display_cluster_config.yml
      vars:
        jboss_cli_controller_port: "{{ 9990 + item }}"
      loop:
        - 0
        - 100
