---
- name: "Move any messages in the DLQ to another queue for processing"
  hosts: all
  gather_facts: False
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Running CLI script to move messages from DLQ to {{ jms_queue }}"
      ansible.builtin.include_role:
        name: wildfly_utils
        tasks_from: jboss_cli.yml
      vars:
        jboss_cli_query: "/subsystem=jgroups/channel=ee:read-attribute(name='stack')"

    - name: "Display result of CLI scripts execution"
      ansible.builtin.debug:
        msg: "{{ cli_result.stdout_lines[2] }}"
      when:
        - cli_result is defined
