---
- name: "Restart Wildfly instance if not running"
  hosts: wildfly
  gather_facts: no
  tasks:
    - name: Restart Wildfly
      ansible.builtin.service:
        name: "wildfly-{{ id }}"
        state: started
      loop:
        - "0"
        - "1"
      loop_control:
        loop_var: id
