---
- name: "React on a message sent by Kafka"
  hosts: keycloak
  gather_facts: true
  vars:
    jboss_home: '/opt/keycloak/keycloak-18.0.2/'
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Printing event details on {{ ansible_nodename }}"
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event }}"
      when:
        - ansible_eda is defined and ansible_eda.event is defined

    - name: "No event provided"
      ansible.builtin.debug:
        msg: "No event provided"
      when:
        - not ansible_eda is defined

    - name: "Add a system property to Keycloak named Javaland={{ ansible_eda.event }}."
      ansible.builtin.include_role:
        name: wildfly_utils
        tasks_from: jboss_cli.yml
      vars:
        jboss_cli_query: "{{ query }}"
      loop:
        - "/system-property=Javaland:remove()"
        - "/system-property=Javaland:add(value=\"{{ ansible_eda.event.body | replace('wildfly ', '') | join | string }}\")"
      loop_control:
        loop_var: query

    - name: "Retrieve new system property value"
      ansible.builtin.include_role:
        name: wildfly_utils
        tasks_from: jboss_cli.yml
      vars:
        jboss_cli_query: "/system-property=Javaland:read-resource()"

    - name: "Display result"
      ansible.builtin.debug:
        var: cli_result.stdout
