---
- name: "Move any messages in the DLQ to another queue for processing"
  hosts: all
  gather_facts: False
  serial: 1
  vars:
    jboss_cli_file: /opt/dql.cli
    jboss_cli_template: templates/dlq.cli.j2
    dlq_name: DLQ
    target_queue: BizQueue
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Generate CLI script from template: {{ jboss_cli_template }}"
      ansible.builtin.template:
        src: "{{ jboss_cli_template }}"
        dest: "{{ jboss_cli_file }}"

    - name: "Running CLI script to move messages from DLQ to {{ jms_queue }}"
      ansible.builtin.include_role: 
        name: wildfly_utils
        tasks_from: jboss_cli.yml

    - name: "Display result of CLI scripts execution"
      ansible.builtin.debug:
        msg: "{{ cli_result.stdout_lines | join | string }}"
      when:
        - cli_result is defined
