---
- name: Install wildfly
  hosts: wildfly
  collections:
    - middleware_automation.wildfly
  vars_files:
    - vars/vars.yml
    - vars/apps.yml
    - vars/jdbc.yml
  pre_tasks:
    - name: "Download apps (if needed)"
      ansible.builtin.get_url:
        url: "{{ app.download_url }}"
        dest: "{{ app.path }}"
      loop: "{{ wildfly_apps }}"
      loop_control:
        loop_var: app
      when:
        - wildfly_apps is defined and wildfly_apps | length > 0
  tasks:
    - name: "Include wildfly_systemd"
      ansible.builtin.include_role:
        name: wildfly_install

- name: Install multiple wildfly services
  hosts: wildfly
  collections:
    - middleware_automation.wildfly
  vars_files:
    - vars/vars.yml
    - vars/apps.yml
    - vars/jdbc.yml
  vars:
    wildfly_remote_destination_outbound_socket_binding:
        wildfly0:
          host: '127.0.0.1'
          port: 7600
        wildfly1:
          host: '127.0.0.1'
          port: 7700
  tasks:
    - ansible.builtin.include_tasks: tasks/systemd_and_jdbc_drivers.yml
